version: "3.9"
  
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "1488:1488"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: { }
